Festival.Web/Areas/Admin/ViewModels/Performer/DetailPerformerVM.cs
namespace Festival.Web.ViewModels.Performer
{
    public class DetailPerformerVM
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public float Fee { get; set; }
        public string PromoText { get; set; }
        public string Picture { get; set; }
        public string ManagerName { get; set; }
        public string ManagerPhoneNumber { get; set; }
        public string ManagerEmail { get; set; }
    }
}

Festival.Web/Areas/Admin/ViewModels/Performer/EditPerformerVM.cs
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;

namespace Festival.Web.ViewModels.Performer
{
    public class EditPerformerVM
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Performer name is required, please insert it.")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Fee is required, please insert the amount.")]
        [Range(1, 5000, ErrorMessage = "Value should be between 1 and 5000 KM.")]
        public float Fee { get; set; }
        [Required(ErrorMessage = "Promo text for the performer is required.")]
        public string PromoText { get; set; }
        public IFormFile Image { get; set; }
        public int ManagerId { get; set; }
        [Required(ErrorMessage = "Manager name is required, please insert it.")]
        public string ManagerName { get; set; }
        [Required(ErrorMessage = "Manager phone number is required, please insert it.")]
        public string ManagerPhoneNumber { get; set; }
        [Required(ErrorMessage = "Manager E-mail is required, please insert it.")]
        public string ManagerEmail { get; set; }
    }
}

Festival.Web/Areas/Admin/ViewModels/Performer/NewPerformerVM.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Festival.Web.ViewModels.Performer
{
    public class NewPerformerVM
    {
        [Required(ErrorMessage = "Performer name is required, please insert it.")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Fee is required, please insert the amount.")]
        [Range(1, float.MaxValue, ErrorMessage = "Value should be greater than 1")]
        public float Fee { get; set; }
        [Required(ErrorMessage = "Promo text for the performer is required.")]
        public string PromoText { get; set; }
        [Required(ErrorMessage = "Picture is required, please pick one.")]
        public IFormFile Image { get; set; }

        public string ManagerName { get; set; }

        public string ManagerPhoneNumber { get; set; }

        public string ManagerEmail { get; set; }
        public List<SelectListItem> Managers { get; set; }
        public int? ManagerId { get; set; }
    }
}

Festival.Web/Areas/Admin/ViewModels/Performer/PerformersListVM.cs
namespace Festival.Web.ViewModels.Performer
{
    public class PerformersListVM
    {
        public int PerformerID { get; set; }
        public int Number { get; set; }
        public string PerformerName { get; set; }
        public string ManagerName { get; set; }
        public float Fee { get; set; }
        public string Contact { get; set; }
    }
}

Festival.Web/Areas/Admin/Controllers/PerformerController.cs
using Festival.Data.Models;
using Festival.Data.Repositories;
using Festival.Web.Helper;
using Festival.Web.ViewModels.Performer;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;

namespace FestivalWebApplication.Controllers
{

    [Area("Admin")]
    public class PerformerController : Controller
    {
        private readonly IPerformerRepository _repo;
        private readonly IWebHostEnvironment _hostingEnvironment;

        public PerformerController(IWebHostEnvironment environment, IPerformerRepository repo, IWebHostEnvironment webHostEnvironment)
        {
            _hostingEnvironment = environment;
            _repo = repo;
        }
        public IActionResult Index()
        {
            return RedirectToAction("List");
        }
        public IActionResult List()
        {
            //fetching all records from Performer
            var model = _repo.GetAll().Select(p => new PerformersListVM
            {
                PerformerID = p.ID,
                PerformerName = p.Name,
                ManagerName = p.Manager.Name,
                Fee = p.Fee,
                Contact = p.Manager.PhoneNumber
            }).ToList();

            //ordered list
            int broj = 0;
            foreach (PerformersListVM x in model)
            {
                x.Number = ++broj;
            }
            return View(model);
        }

        public IActionResult New()
        {
            NewPerformerVM Model = new NewPerformerVM();
            Model.Managers = _repo.GetAllManagers().Select(m => new SelectListItem
            {
                Value = m.ID.ToString(),
                Text = m.Name
            }).ToList();

            return View(Model);
        }

        public IActionResult SaveNew(NewPerformerVM model)
        {
            if (!ModelState.IsValid)
            {
                return View("New");
            }
            //creating new manager object 
            var manager = new Manager
            {
                Name = model.ManagerName,
                PhoneNumber = model.ManagerPhoneNumber,
                Email = model.ManagerEmail
            };
            //adding new manager into the database if the chosen id is 9999 (aka none of the given options)
            if (model.ManagerId == 9999)
            {
                //adding new manager to db first, to be able to assign managerID to a performer
                _repo.AddManager(manager);
            }

            var uniqueFileName = Image.Upload(model.Image, _hostingEnvironment, "performers");

            var performer = new Performer
            {
                Name = model.Name,
                Fee = model.Fee,
                PromoText = model.PromoText,
                ManagerID = model.ManagerId,
                Picture = uniqueFileName
            };
            if (model.ManagerId == 9999)
                performer.ManagerID = manager.ID;

            _repo.Add(performer);

            return RedirectToAction("List");
        }

        public IActionResult Edit(int id)
        {
            var performer = _repo.GetByID(id);

            var model = new EditPerformerVM
            {
                Id = performer.ID,
                Name = performer.Name,
                Fee = performer.Fee,
                PromoText = performer.PromoText,
                ManagerId = performer.Manager.ID,
                ManagerName = performer.Manager.Name,
                ManagerPhoneNumber = performer.Manager.PhoneNumber,
                ManagerEmail = performer.Manager.Email
            };

            return View("Edit", model);

        }
        public IActionResult Save(EditPerformerVM model)
        {
            if (!ModelState.IsValid)
            {
                return View("Edit");
            }

            var manager = _repo.FindManagerById(model.ManagerId);

            manager.Name = model.ManagerName;
            manager.Email = model.ManagerEmail;
            manager.PhoneNumber = model.ManagerPhoneNumber;

            _repo.Save();

            var performer = _repo.GetByID(model.Id);
            performer.Name = model.Name;
            performer.Fee = model.Fee;
            performer.PromoText = model.PromoText;

            if (model.Image != null)
            {
                var uniqueFileName = Image.Upload(model.Image, _hostingEnvironment, "performers");
                performer.Picture = uniqueFileName;
            }

            _repo.Save();
            return RedirectToAction("List");

        }

        public IActionResult Detail(int id)
        {
            var performer = _repo.GetByID(id);
            var model = new DetailPerformerVM
            {
                Id = performer.ID,
                Fee = performer.Fee,
                Name = performer.Name,
                PromoText = performer.PromoText,
                Picture = performer.Picture,
                ManagerName = performer.Manager.Name,
                ManagerPhoneNumber = performer.Manager.PhoneNumber,
                ManagerEmail = performer.Manager.Email
            };

            return View("Detail", model);
        }
        public IActionResult Delete(int id)
        {
            var performer = _repo.GetByID(id);
            Image.Delete(_hostingEnvironment, "performers", performer.Picture);
            _repo.Delete(id);
            return RedirectToAction("List");
        }
    }


}

Festival.Web/Areas/Admin/Views/Performer/Detail.cshtml
@using Microsoft.EntityFrameworkCore.Metadata.Internal
@model Festival.Web.ViewModels.Performer.DetailPerformerVM;
@{
    ViewData["Title"] = Model.Name;
}

<div class="col-6" style="float:left">
    <h2 class="detailName">@Model.Name</h2>
    <div class="form-group row detailRow">
        <label class="detailLabel" for="Fee">Performer fee : </label>
        <span class="detailData">@Model.Fee KM</span>
    </div>
    <div class="form-group row detailRow">
        <label class="detailLabel" for="PromoText">Promo text : </label>
        <span class="detailData">@Model.PromoText</span>
    </div>
    <br />
    <h4 class="detailName">Manager Info:  </h4>
    <div class="form-group row detailRow">
        <label class="detailLabel" for="ManagerPhoneNumber">Manager name : </label>
        <span class="detailData">@Model.ManagerName</span>
    </div>
    <div class="form-group row detailRow">
        <label class="detailLabel" for="ManagerPhoneNumber">Manager phone number : </label>
        <span class="detailData">@Model.ManagerPhoneNumber</span>
    </div>
    <div class="form-group row detailRow">
        <label class="detailLabel" for="ManagerEmail">Manager e-mail : </label>
        <span class="detailData">@Model.ManagerEmail</span>
    </div>
    <div class="detailButtons btn-group">
        <a style="margin-right:5px;" asp-controller="Performer" asp-action="List" class="btn btn-info active" role="button" aria-pressed="true">
            Back
            <i class="fa fa-undo"></i>
        </a>
        <a style="margin-right:5px;" asp-controller="Performer" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-secondary active" role="button" aria-pressed="true">
            Edit
            <i class="fa fa-edit"></i>
        </a>
        <a asp-controller="Performer" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger" role="button" aria-pressed="true">
            Delete
            <i class="fa fa-trash"></i>
        </a>
    </div>
</div>
<div class="col-6 " style="float:right">
    <img src="~/images/performers/@Model.Picture" class="accImage imageDiv" />
</div>

<div class="clearfix"></div>

Festival.Web/Areas/Admin/Views/Performer/Edit.cshtml
@model Festival.Web.ViewModels.Performer.EditPerformerVM;
@{
    ViewData["Title"] = Model.Name;
}



<style>





    .container {
        padding: 0 !important;
    }

    main.pb-3 {
        padding-bottom: 0 !important;
    }
</style>

<div class="formDiv" style="background-color:#e2e2e2;">
    <form class="formMy" style="border:2px dotted #fafafa; background-color:#fafafa" asp-action="Save" enctype="multipart/form-data" method="post">
        <fieldset>
            <legend class="w-auto">Performer</legend>
            <input asp-for="Id" hidden />
            <div class="form-group newRow">
                <label for="Name" class="newLabel">Name :</label>
                <div>
                    <input asp-for="Name" class="form-control" />
                </div>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group newRow">
                <label for="PromoText" class="newLabel">Promotional text :</label>
                <div>
                    <textarea asp-for="PromoText" class="form-control" rows="3" style="height:100%"> </textarea>
                </div>
                <span asp-validation-for="PromoText" class="text-danger"></span>
            </div>


            <div class="form-group newRow">
                <div>
                    <label class="newLabel" for="Fee">Festival fee (KM) :</label>
                    <input asp-for="Fee" class="form-control col-3" />
                </div>
                <span asp-validation-for="Fee" class="text-danger"></span>
            </div>

            <label class="newLabel" for="Image">Image : </label>
            <div class="custom-file newRow">
                <div>
                    <input asp-for="Image" class="form-control custom-file-input col-6" />
                    <label class="custom-file-label" for="Image">Choose image</label>
                </div>
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="clearfix"></div>
        </fieldset>

        <fieldset>
            <legend class="w-auto">Manager</legend>

            <input asp-for="ManagerId" hidden />
            <div class="form-group newRow">
                <label for="ManagerName" class="newLabel">Name :</label>
                <div>
                    <input asp-for="ManagerName" class="form-control" />
                </div>
                <span asp-validation-for="ManagerName" class="text-danger"></span>
            </div>

            <div class="form-group newRow">
                <label for="ManagerEmail" class="newLabel">Email :</label>
                <div>
                    <input asp-for="ManagerEmail" type="email" class="form-control" />
                </div>
                <span asp-validation-for="ManagerEmail" class="text-danger"></span>
            </div>

            <div class="form-group newRow">
                <label for="ManagerPhoneNumber" class="newLabel">Phone Number :</label>
                <div>
                    <input asp-for="ManagerPhoneNumber" class="form-control col-6" />
                </div>
                <span asp-validation-for="ManagerPhoneNumber" class="text-danger"></span>
            </div>

        </fieldset>
        <div class="btn-group">
            <a style="margin-right:5px;" asp-controller="Performer" asp-action="List" class="btn btn-info active" role="button" aria-pressed="true">
                Back
                <i class="fa fa-undo"></i>
            </a>
            <a asp-controller="Performer" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger" role="button" aria-pressed="true">
                Delete
                <i class="fa fa-trash"></i>
            </a>
            <input type="submit" value="Save changes" class="btn btn-secondary submit ml-1" />
        </div>


    </form>
</div>

Festival.Web/Areas/Admin/Views/Performer/List.cshtml
@using Festival.Web.ViewModels.Performer;
@model List<Festival.Web.ViewModels.Performer.PerformersListVM>
@{
    ViewData["Title"] = "Performers";
}

<h1>Performers</h1>
<div style="float:right; margin-bottom:10px;">
    <a asp-controller="Performer" asp-action="New" class="btn btn-success btn-lg active" role="button" aria-pressed="true">Add New <i class="fa fa-plus"></i></a>
</div>
<table class="table table-striped table-hover text-center ">
    <thead class="thead-dark">
        <tr>
            <th>#</th>
            <th>Performer</th>
            <th>Fee</th>
            <th>Manager</th>
            <th>Contact</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (PerformersListVM x in Model)
        {
            <tr>
                <td>@x.PerformerID</td>
                <td>@x.PerformerName</td>
                <td>@x.Fee KM</td>
                <td>@x.ManagerName</td>
                <td>@x.Contact</td>
                <td>
                    <div class="btn-group">
                        <a style="margin-right:5px;" asp-controller="Performer" asp-action="Detail" asp-route-id="@x.PerformerID" class="btn btn-info active btn-sm" role="button" aria-pressed="true">
                            <i class="fa fa-info mr-1"></i>
                            Detail
                        </a>
                        <a style="margin-right:5px;" asp-controller="Performer" asp-action="Edit" asp-route-id="@x.PerformerID" class="btn btn-secondary active btn-sm" role="button" aria-pressed="true">
                            <i class="fa fa-edit"></i>
                            Edit
                        </a>
                        <a asp-controller="Performer" asp-action="Delete" asp-route-id="@x.PerformerID" class="btn btn-danger btn-sm" role="button" aria-pressed="true">
                            <i class="fa fa-trash"></i>
                            Delete
                        </a>
                    </div>
                </td>
            </tr>

        }
    </tbody>
</table>

Festival.Web/Areas/Admin/Views/Performer/New.cshtml
@model Festival.Web.ViewModels.Performer.NewPerformerVM;
@{
    ViewData["Title"] = "New Performer";
}
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/Inputmask-5.x/dist/jquery.inputmask.js"></script>

<style>

    .container {
        padding: 0 !important;
    }

    main.pb-3 {
        padding-bottom: 0 !important;
    }
</style>

<div class="formDiv" style="background-color:#e2e2e2;">
    <form class="formMy" style="border:2px dotted #fafafa; background-color:#fafafa" asp-action="SaveNew" enctype="multipart/form-data" method="post">

        <fieldset>
            <legend class="w-auto">Performer</legend>
            <div class="form-group newRow">
                <label for="Name" class="newLabel">Name :</label>
                <div>
                    <input asp-for="Name" class="form-control" />
                </div>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group newRow">
                <label for="Fee" class="newLabel">Fee (KM) :</label>
                <div>
                    <input asp-for="Fee" class="form-control col-3" />
                </div>
                <span asp-validation-for="Fee" class="text-danger"></span>
            </div>

            <div class="form-group newRow">
                <label class="newLabel" for="PromoText">Promo text :</label>
                <div>
                    <textarea asp-for="PromoText" class="form-control" rows="4"></textarea>
                </div>
                <span asp-validation-for="PromoText" class="text-danger"></span>
            </div>

            <label class="newLabel" for="Image">Image : </label>
            <div class="custom-file newRow">
                <div>
                    <input asp-for="Image" class="form-control custom-file-input col-6" />
                    <label class="custom-file-label" for="Image">Choose image</label>
                </div>
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>

        </fieldset>

        <fieldset>
            <legend class="w-auto">Manager</legend>
            <span class="font-italic small">Choose a manager from the list or insert new manager data</span>
            <div class="clearfix"></div>

            <div class="form-group newRow">
                <select asp-items="@Model.Managers" asp-for="ManagerId" class="form-control">
                    <option selected value="9999">(None of the listed)</option>
                </select>

            </div>
            <div class="form-group newRow">
                <label class="newLabel" for="ManagerName">Name :</label>
                <div>
                    <input asp-for="ManagerName" class="form-control" />
                </div>
                <span asp-validation-for="ManagerName" class="text-danger"></span>
            </div>

            <div class="form-group newRow">
                <label class="newLabel" for="ManagerPhoneNumber">Phone number :</label>
                <div>
                    <input asp-for="ManagerPhoneNumber" class="form-control" />
                </div>
                <span asp-validation-for="ManagerPhoneNumber" class="text-danger"></span>
            </div>

            <div class="form-group newRow">
                <label class="newLabel" for="ManagerEmail">Email :</label>
                <div>
                    <input asp-for="ManagerEmail" class="form-control" id="email"/>
                </div>
                <span asp-validation-for="ManagerEmail" class="text-danger"></span>
            </div>

        </fieldset>

        <div class="btn-group">
            <a style="margin-right:5px;" asp-controller="Performer" asp-action="List" class="btn btn-info active" role="button" aria-pressed="true">
                Back
                <i class="fa fa-undo"></i>
            </a>
            <input type="submit" value="Save new" class="btn btn-lg btn-secondary submit ml-1" />
        </div>

    </form>
</div>
<script>
    $(function ($) {
        $("#email").inputmask({
            mask: "*{1,20}[.*{1,20}][.*{1,20}][.*{1,20}]@@*{1,20}[.*{2,6}][.*{1,2}]",
            greedy: false,
            onBeforePaste: function (pastedValue, opts) {
                pastedValue = pastedValue.toLowerCase();
                return pastedValue.replace("mailto:", "");
            },
            definitions: {
                '*': {
                    validator: "[0-9A-Za-z!#$%&'*+/=?^_`{|}~\-]",
                    casing: "lower"
                }
            }
        });
    })
</script>